### ISSUE TITLE
react js 模版，本地yarn start，资源404

### ISSUE THREAD

**Issue by lzs246** [tnfe/hel#11]
依赖版本：
<img width="246" alt="image" src="https://user-images.githubusercontent.com/62453543/188310746-a5e603ec-c9c5-4072-8ae0-5a70048e5d50.png">
报错信息：
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/62453543/188310771-c9d857f7-3b78-49a7-8055-9123ce4d88c7.png">

复现仓库：https://github.com/lzs246/hel-react-remote
复现步骤：
1.安装依赖
2.yarn start

**Comment by lzs246** [comment]
产物里面没有build
<img width="290" alt="image" src="https://user-images.githubusercontent.com/62453543/188311093-7a786dbe-96e5-4573-b54e-6b7cf6c65b93.png">

**Comment by fantasticsoul** [comment]
hel_dist 就是build的产物

**Comment by fantasticsoul** [comment]
反应过来了，你说的是没有 `bundle`

**Comment by fantasticsoul** [comment]
你好，根据最新的react组件模板试试，应该没问题了 
https://github.com/hel-eco/hel-tpl-remote-react-comp

**Comment by lzs246** [comment]
感谢大佬
