### ISSUE TITLE
hel-micro是解决什么问题的？

### ISSUE THREAD

**Issue by codepandy** [tnfe/hel#12]
你好：
看了你们的文档，还是不明白hel-micro是想解决什么问题，是解决的js模块的动态加载吗？是因为es6的动态import不友好做的替代方案吗？
看文档上说，“通过规范打包协议实现模块联邦sdk化. 和模块使用方工具链无关”
这是说打包的时候实现模块联邦sdk化吗？是通过hel-micro实现还是说micro具备这样的特性？模块联邦不是webpack5的功能吗？

**Comment by fantasticsoul** [comment]
你好，可以阅读这篇文章了解
https://juejin.cn/post/7138792768234586148

**Comment by fantasticsoul** [comment]
模块联邦 是一个概念，webpack 对其做了具体实现，vite也有对应的实现`vite-federation-plugin`，而 hel-micro 是从语法层面去实现，脱离了工具链的捆绑，提高模块的流通性，降低模块联邦的准入门槛。

**Comment by fantasticsoul** [comment]
答复见上面留言哈，我先关闭issue了
