### ISSUE TITLE
交互响应似乎很慢

### ISSUE THREAD

**Issue by xujie-phper** [tnfe/hel#15]
用demo体验了下，交互时，动态去加载资源，然后执行逻辑，链路有点长，响应很慢啊，用户体验好像不太好，是我使用方式不对么

**Comment by fantasticsoul** [comment]
加载逻辑是很快的，关键是 unpkg 服务在国内响应比较慢，实际使用建议发布到自己的cdn服务器，或者推荐一个国内的比较快的cdn服务给我，hel内置支持

**Comment by fantasticsoul** [comment]
可以clone到本地试试，浏览器缓存文件后，就非常快乐

**Comment by fantasticsoul** [comment]
相关提速方案已出，可见这个用户的总结
https://github.com/tnfe/hel/issues/19

**Comment by starsoul666** [comment]
> 相关提速方案已出，可见这个用户的总结 #19

这个链接打不开了
