### ISSUE TITLE
支持关闭404嗅探

### ISSUE THREAD

**Issue by lyh0371** [tnfe/hel#23]
场景：404嗅探虽然不影响功能， 但是会被监控平台统计到，可能影响运营系统报警
希望：支持用户手动关闭404嗅探

**Comment by fantasticsoul** [comment]
hel-micro `3.9.4`已支持，见提交：
https://github.com/tnfe/hel/commit/ef746132e52cdd807167a0b9d046454409aaaa30

**Comment by fantasticsoul** [comment]
404 嗅探存在的原因：

这个机制是因为 unpkg 的语义化版本的最新版本参数 latest 生效不及时才加的这个 404 请求
举个例子，假如 hel-lodash 版本为 2.1.7 我期望的：
https://unpkg.com/hel-lodash@latest/hel_dist/hel-meta.json
就马上返回的是 2.1.7 版本的元数据
https://unpkg.com/hel-lodash@2.1.7/hel_dist/hel-meta.json

如果此时我发布了2.1.8， 再访问 https://unpkg.com/hel-lodash@latest/hel_dist/hel-meta.json，依然返回 https://unpkg.com/hel-lodash@2.1.7/hel_dist/hel-meta.json
如果我用一个404嗅探，https://unpkg.com/hel-lodash/xxxxx-not-found 则会返回 https://unpkg.com/hel-lodash@2.1.8/xxxxx-not-found，此时hel-micro就可以提取到 2.1.8 作为最新的版本参数去请求元数据了

**Comment by wenshuangz** [comment]
> 404 嗅探存在的原因：
> 
> 这个机制是因为 unpkg 的语义化版本的最新版本参数 latest 生效不及时才加的这个 404 请求 举个例子，假如 hel-lodash 版本为 2.1.7 我期望的： https://unpkg.com/hel-lodash@latest/hel_dist/hel-meta.json 就马上返回的是 2.1.7 版本的元数据 https://unpkg.com/hel-lodash@2.1.7/hel_dist/hel-meta.json
> 
> 如果此时我发布了2.1.8， 再访问 [https://unpkg.com/hel-lodash@latest/hel_dist/hel-meta.json，依然返回](https://unpkg.com/hel-lodash@latest/hel_dist/hel-meta.json%EF%BC%8C%E4%BE%9D%E7%84%B6%E8%BF%94%E5%9B%9E) https://unpkg.com/hel-lodash@2.1.7/hel_dist/hel-meta.json 如果我用一个404嗅探，https://unpkg.com/hel-lodash/xxxxx-not-found 则会返回 [https://unpkg.com/hel-lodash@2.1.8/xxxxx-not-found，此时hel-micro就可以提取到](https://unpkg.com/hel-lodash@2.1.8/xxxxx-not-found%EF%BC%8C%E6%AD%A4%E6%97%B6hel-micro%E5%B0%B1%E5%8F%AF%E4%BB%A5%E6%8F%90%E5%8F%96%E5%88%B0) 2.1.8 作为最新的版本参数去请求元数据了

咨询一下，如果设置skip404Sniff:true，会影响更新时效性么？有多大？
