### ISSUE TITLE
期待 vite + vue的模板~

### ISSUE THREAD

**Issue by wenshuangz** [tnfe/hel#25]

**Comment by fantasticsoul** [comment]
没问题，会及时补上的

**Comment by wenshuangz** [comment]
嗯嗯，最近打算先从lib入手尝试，后续逐渐切入vite + vue2/3😄

**Comment by fantasticsoul** [comment]
见示例：https://github.com/hel-eco/hel-tpl-remote-vue3-comps-ts

**Comment by fantasticsoul** [comment]
codesandbox使用示例也提供了：
https://codesandbox.io/s/demo-load-remote-vue3-comp-2fd34s?file=/src/main.js
