### ISSUE TITLE
hel vue2 升级 vue3 运行时提示问题

### ISSUE THREAD

**Issue by wenshuangz** [tnfe/hel#26]
hel vue2 升级 vue3 运行时提示问题警告，这是说hel目前支持vue2？

 ****** [hel-runtime/level1-vue vue and others] ******
v1-2.6.14-vue.js:7541  vue: 2.6.14

![image](https://user-images.githubusercontent.com/27257365/195001426-c4c1700b-b28c-458e-8c1f-706fc6c30cc2.png)

**Comment by fantasticsoul** [comment]
你好，尝试将 public/index.html 里的 vue cdn链接换为这个再试试看呢
https://tnfe.gtimg.com/hel-runtime/level1/3.2.33-vue.js

**Comment by wenshuangz** [comment]
升级后提示这个
 ****** [hel-runtime/level1-vue vue and others] ******
3.2.33-vue.js:64941  vue,@vue/compiler-dom,@vue/compiler-sfc,@vue/runtime-core,@vue/runtime-dom,@vue/shared,@vue/reactivity: 3.2.33

**Comment by fantasticsoul** [comment]
貌似vue2和vue3组件模板不能通用，我基于 @vue/cli 重新创建一个vue3的远程组件模板吧😭

**Comment by wenshuangz** [comment]
万分感激，大佬什么时候搞vue3模板，等米下锅😄

**Comment by fantasticsoul** [comment]
> 万分感激，大佬什么时候搞vue3模板，等米下锅😄

正在搞了，支持以 webpack 和 vite 两种模式开发，打包还是用webpack

**Comment by fantasticsoul** [comment]
模板出炉了：
https://github.com/hel-eco/hel-tpl-remote-vue3-comps-ts

**Comment by fantasticsoul** [comment]
codesandbox使用示例也提供了：
https://codesandbox.io/s/demo-load-remote-vue3-comp-2fd34s?file=/src/main.js
