### ISSUE TITLE
【咨询】如果设置skip404Sniff:true，会影响更新时效性么？有多大？

### ISSUE THREAD

**Issue by wenshuangz** [tnfe/hel#28]

**Comment by fantasticsoul** [comment]
群里有小伙伴搭了私服说是没有延迟，我用的公网的unpkg，感觉有点延迟才加了这个404嗅探，你可以关闭试试

欢迎入群了解更多
![image](https://user-images.githubusercontent.com/7334950/195076193-90532e51-47a9-47bb-be40-d13069018f0a.png)
