### ISSUE TITLE
unpkg私服编译后产物不带当前包的版本号

### ISSUE THREAD

**Issue by sunyuelei** [tnfe/hel#30]
subApp.js中设置cdn前缀后，在unpkg私服下打包后的地址中不带版本号

**Comment by fantasticsoul** [comment]
更新到 hel-dev-utils 到 2.3.4 解决此问题，配置可参考这里 https://github.com/hel-eco/hel-lodash/blob/main/config/subApp.js

**Comment by Camusama** [comment]
hel-tpl-remote-react-comps-ts 模板也需要更新 hel-dev-utils
