### ISSUE TITLE
[docs] 用户获取模板库时候建议改为 degit

### ISSUE THREAD

**Issue by Otto-J** [tnfe/hel#33]
degit https://www.npmjs.com/package/degit 是一个常用的工具，可以快速下载远程仓库或者仓库里文件夹。

建议文档中从 git clone 改为 npx degit 这样有两个好处
- 用户下载的模板是纯文件夹，没有 git commit 提交历史，自行 git init 提交更干净
- 后续可以拆分为多个文件夹，对应不同的模板，下载时候下载对应的文件夹，有更好的拓展性

**Comment by Otto-J** [comment]
或许我可以提交 pr 来完善这部分文档

**Comment by Otto-J** [comment]
- https://github.com/hel-eco/hel-tpl-remote-react-comp-ts.git
- https://github.com/hel-eco/hel-tpl-remote-lib
- https://github.com/hel-eco/hel-tpl-remote-react-comp

这三个仓库就可以合并为一个了，比如 /hel-eco/template。对应不同的文件夹
- /hel-react-comp-ts
- /hel-lib
- /hel-react-comp

下载时候使用 `npx degit hel-eco/template/hel-lib self-hel-lib `来下载指定的模板

**Comment by fantasticsoul** [comment]
已合并并发布：https://tnfe.github.io/hel/docs/tutorial/helmod-dev/
