### ISSUE TITLE
[feature] 针对国内用户提供 gitee 源备份

### ISSUE THREAD

**Issue by Otto-J** [tnfe/hel#35]
# 背景
本项目会提供一些模板供用户下载使用，做到了开箱即用。也因为众所周知的原因，国内用户下载远程内容时候，时常卡死直到超时。用户体验不好。

# 解决思路

考虑到这种情况，建议可以同时维护一份 gitee 官方仓库，通过修改 github action 自动将 main 分支的提交同步到 gitee 。这样下载模板时候提供两套源，保证随时可用。

比如 https://github.com/ShixiangWang/sync2gitee 提供了一些设计思路，这会设计到 .github/workflows 的一些更改。

**Comment by Otto-J** [comment]
如果这样操作，需要做两件事：
- 注册建立 gitee 仓库
- 修改 github actions

**Comment by fantasticsoul** [comment]
仓库：https://gitee.com/fantasticsoul/hel

已配置镜像同步（github-->gitee）
![image](https://user-images.githubusercontent.com/7334950/197433530-75526284-1924-4751-a90e-41e7cd3d21dd.png)

**Comment by Otto-J** [comment]
后续持续改进，项目启动的用户体验
- 用户更容易地迈出第一步，比如 https://github.com/tiged/tiged 下载 gitee 
- 非高优，cli 自动判断区分
- demo 修改的信息进一步解释，简化修改逻辑，比如 loadEnv

具体的我单独 issue 里展开
