### ISSUE TITLE
hel-micro与无界一起用会报错

### ISSUE THREAD

**Issue by sunyuelei** [tnfe/hel#38]
项目里面既用了wujie又用了hel-micro会报错,导致两个都不能用，报错信息如下

**Comment by sunyuelei** [comment]
![20221111-145554](https://user-images.githubusercontent.com/24217000/201281465-51be6155-bc9d-4a0d-9883-bd874efcb3ff.jpeg)

**Comment by fantasticsoul** [comment]
经沟通，是wujie的问题，贡献示例后解决

<img width="509" alt="image" src="https://user-images.githubusercontent.com/7334950/201327337-39cd3468-43b0-4511-8657-a8c757588619.png">
