### ISSUE TITLE
[Bug]类型错误

### ISSUE THREAD

**Issue by freespace8** [tnfe/hel#39]
运行程序时，类型错误
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/4084411/201454544-daf1cb27-afba-4f90-a2c7-05415c1007ef.png">

**Comment by fantasticsoul** [comment]
fixed: https://github.com/tnfe/hel/commit/251fa04a5c49c1d898b2ecaa3022ae12fcffa1b7
