### ISSUE TITLE
惰性加载远程模块报错

### ISSUE THREAD

**Issue by jeff-fe** [tnfe/hel#4]
<img width="720" alt="image" src="https://user-images.githubusercontent.com/19850462/187863652-b937a654-d113-48f7-ae55-b73c270021db.png">

<img width="606" alt="image" src="https://user-images.githubusercontent.com/19850462/187862910-516525d9-dc14-476b-8bae-60366b1fdf80.png">

**Comment by fantasticsoul** [comment]
你好，提供下 hel-micro 版本哈

**Comment by jeff-fe** [comment]
赞👍🏻
