### ISSUE TITLE
本地启动hel-tpl-remote-vue3-comps-ts ,调试时主应用无法加载

### ISSUE THREAD

**Issue by wukai900610** [tnfe/hel#40]
![image](https://user-images.githubusercontent.com/3339632/202594241-fa267f68-e1fa-45a4-925e-bf23deb5fa44.png)

**Comment by fantasticsoul** [comment]
看下network呢，是否能正常请求到js资源，截图看下哈

**Comment by fantasticsoul** [comment]
建议把 code sandbox 代码clone下来本地跑，codesanbox联调本地需要不停换端口，端口用一次后再连的需要换一个（应该是内部的某种保护机制）

**Comment by wukai900610** [comment]
感谢大佬 例子放在本地可以成功运行了 
但有个新问题 主应用是vite启动的,远程组件hel-tpl-remote-vue3-comps-ts,  npm run start:vite后 无法正常本地联调

**Comment by fantasticsoul** [comment]
和是不是vite没关系的，你可以把你的项目提交下么，我试试呢

**Comment by wukai900610** [comment]
https://gitee.com/wk365/demo.git 复现的最小例子 大佬看下呢

**Comment by wukai900610** [comment]
https://gitee.com/wk365/demo.git 复现的最小例子 大佬看下呢

**Comment by fantasticsoul** [comment]
好的，晚上我看下

**Comment by fantasticsoul** [comment]
> https://gitee.com/wk365/demo.git 复现的最小例子 大佬看下呢

你好，你的主项目里联调端口号写错了（我把代码拉下来发现子模块运行的是7001端口）：
![image](https://user-images.githubusercontent.com/7334950/206828830-9ce500a3-2059-4e77-8b5c-d031f4aacc19.png)

然后你在子模块里执行 `npm i  hel-lib-proxy@latest`，主项目里执行 `npm i  hel-micro@latest` 即可正常联调，最新版本已适配 vite

**Comment by fantasticsoul** [comment]
> https://gitee.com/wk365/demo.git 复现的最小例子 大佬看下呢

在你的setup文件里导入远程组件后
<img width="621" alt="image" src="https://user-images.githubusercontent.com/7334950/206829016-9d3e0b33-bfcf-4bf2-bdcb-cf64e59e6197.png">

模板里这样写：
<img width="391" alt="image" src="https://user-images.githubusercontent.com/7334950/206829031-b641c3c8-50f0-42db-ac9c-43fbc0aa7edb.png">

本地已正常渲染出来
![image](https://user-images.githubusercontent.com/7334950/206829198-ae32d0ef-6cac-466d-aecf-33f5051aed62.png)

**Comment by fantasticsoul** [comment]
欢迎入群哈，方便沟通
![image](https://user-images.githubusercontent.com/7334950/206829437-f2ce361a-0b8e-4b1d-a4c7-75c322ae4ecc.png)
