### ISSUE TITLE
该库是不是常见使用场景就是针对营销低代码平台搭建使用？

### ISSUE THREAD

**Issue by Renderz** [tnfe/hel#42]
看了一遍文档和案例，还不是太能联想到比较常见的使用场景。似乎低代码平台比较适合？请问是否还有其他场景。

**Comment by fantasticsoul** [comment]
需要跨多个项目动态共享的业务公共依赖模块都特别适合（免去发版后通知使用方构建才能更新逻辑）
 
<img width="722" alt="image" src="https://user-images.githubusercontent.com/7334950/210757025-8a27c249-693f-456e-84ef-6e27ae98cea1.png">
