### ISSUE TITLE
createVue2SubApp传递相对路径

### ISSUE THREAD

**Issue by HUANGSHENGBO** [tnfe/hel#43]
希望可以支持在createVue2SubApp时homePage传递相对路径以满足生产环境与测试环境分开单独部署的功能，感谢

**Comment by fantasticsoul** [comment]
收到建议，近期会加上

**Comment by fantasticsoul** [comment]
在内测了，很快就发布此特性了

**Comment by HUANGSHENGBO** [comment]
👍

**Comment by fantasticsoul** [comment]
已支持，见链接描述（需升级到最新版本的hel-dev-utils）
https://github.com/hel-eco/hel-tpl-remote-vue-comp/blob/master/subApp.js
