### ISSUE TITLE
基于hel-tpl-remote-vue3-comps-ts 模版添加element-plus二次封装的Table组件有data，但没有渲染出来

### ISSUE THREAD

**Issue by yin2017168** [tnfe/hel#45]
![image](https://user-images.githubusercontent.com/26922373/219245830-e79c85a5-d9c8-4b1b-a1cb-21047ac062e9.png)

**Comment by fantasticsoul** [comment]
你的vue是2.*版本的吗，如果是的需要宿主将vue升级到最新的 2.7+ 版本

**Comment by yin2017168** [comment]
后面发现是由于传递的props问题所致

**Comment by fantasticsoul** [comment]
好的
