### ISSUE TITLE
【咨询】是否能将自定义的ReactHooks函数作为微模块方法提供出去

### ISSUE THREAD

**Issue by missfine** [tnfe/hel#46]
在开发联调阶段，能否做到将自定义的的ReactHooks函数，作为微模块的方法提供出去。如果可以的话大致是如何引入调用的。

**Comment by fantasticsoul** [comment]
可以啊，参考模板：
https://github.com/hel-eco/hel-tpl-remote-lib

你可以暴露任何东西（包括react hook）

**Comment by fantasticsoul** [comment]
你好，没有任何问题，你需要再入口文件先执行 preFetchLib，然后其他任何地方都可以这样使用你的远程模块啦。

**Comment by fantasticsoul** [comment]
欢迎入群了解哈，可以更方便交流
