### ISSUE TITLE
【咨询】为啥webpack要打包出html，不是打包出运行时的js就行了吗

### ISSUE THREAD

**Issue by yokiyokiyoki** [tnfe/hel#47]
如题，【咨询】为啥webpack要打包出html，不是打包出运行时的js就行了吗？然后再配合以元数据，就可以拉取位置，顺序等。如果我换成rollup，或者其他工具去打包，应该也是一样的原理吧，看了下打包出了非常多的产物

**Comment by fantasticsoul** [comment]
html是一个辅助提取元数据的产物，同时也是某些场合下提供给微容器载入的入口（例如乾坤等，需要以html地址载入子应用），此时模块是一个独立的大应用。

rollup适合打包库，打包web项目的话还是webpack稳妥些。

**Comment by yokiyokiyoki** [comment]
明白了，我是以wujie作为容器应用的，把hel当成远程模块使用，一时忽略了hel也是可以作为应用的。不过还是建议如果有专门打包远程模块的模式会更好，其他打包工具可以迅速接入。

**Comment by fantasticsoul** [comment]
很快会补齐这一块的文档拉

**Comment by yokiyokiyoki** [comment]
期待，如果这个打包远程模块接入文档起来的话，那么生态应该会迅速起来了🎆

**Comment by fantasticsoul** [comment]
事实上我发布这些远程组件都可以通过html独立访问的，你可以试试
https://unpkg.com/hel-tpl-remote-react-comps@0.2.3/hel_dist/index.html
https://unpkg.com/hel-tpl-remote-vue-comps@1.1.3/hel_dist/index.html 


<img width="1059" alt="image" src="https://user-images.githubusercontent.com/7334950/221201499-47b30226-388b-40f9-8c5a-8501006b2340.png">

!isSubApp 是[本地开发](https://github.com/hel-eco/hel-tpl-remote-vue-comp/blob/master/src/main.js)是用的，但是提供给独立js运行时（例如iframe）也能命中

**Comment by fantasticsoul** [comment]
有个小细节，hel将产物分为静态产物和动态产物，例如这个页面的
https://unpkg.com/hel-tpl-remote-react-comps@0.2.3/hel_dist/index.html 的源码里图里的红箭头是静态产物（他不会随着构建而变化），
<img width="744" alt="image" src="https://user-images.githubusercontent.com/7334950/221203043-73a5c0af-cbf9-4ff6-9a0a-820d5c800d4d.png">

hel-meta.json提取的的交给宿主加载的文件仅是动态产物（那些unpkg.com开头的产物），所以需要宿主提供运行时来驱动组件渲染：https://codesandbox.io/s/demo-load-remote-react-comp-2bnpl0

但是如果以html交给iframe的话，那么就是使用自带的静态产物来驱动渲染了。
https://unpkg.com/hel-tpl-remote-react-comps@0.2.3/hel_dist/index.html

这也是为什么使用wepack打包运行时代码的原因之一，webpack更面向web更全面，打包更灵活。
