### ISSUE TITLE
关于动态更新的隐患

### ISSUE THREAD

**Issue by renlindong** [tnfe/hel#48]
<img width="836" alt="image" src="https://user-images.githubusercontent.com/20882991/222945544-537c6b10-ae3f-43f1-a4e0-3cb2075cbff9.png">

假设项目依赖了远程模块A，按文档上来说默认会加载最新的，当A发布了一个break change的版本，暴露出的某些属性/方法可能删除了，这个时候调用这些方法会出错吧。

**Comment by fantasticsoul** [comment]
所以你可以锁定版本（这个版本号又后台下发，注入到window上）呀，当你测试环境验证新版没问题后，你只需要后台配置中心修改一下版本号，前端依然不用构建重发布，能够运行最新代码。

我们是内网使用，默认采取相信对方模块的原则才不锁版本的。

**Comment by renlindong** [comment]
> 
这样很多js文件的请求都成串行了吧
