### ISSUE TITLE
能否支持修改注入脚本的window指向？

### ISSUE THREAD

**Issue by energy718** [tnfe/hel#51]
场景是 需要在画布的iframe中引入远程模块库，但是引入后样式挂载在外部window上无法进行样式同步

**Comment by fantasticsoul** [comment]
你好，按道理来说，你在 iframe 里载入远程模块，样式应该是挂到 iframe里的，你需要在外部使用的话，再次载入重新载入远程模块就可以了（因为 iframe 和 外面是两个独立的js运行时，需要各自独立引入）

**Comment by fantasticsoul** [comment]
如果你有此类特殊需求，你可以在远程组件载入成功后，调用 
```
import { appStyleSrv } from 'hel-micro';

appStyleSrv.getStyleUrlList(); // 获得样式列表做额外操作

```

**Comment by energy718** [comment]
> 

感谢回复 我按照您的方法试试看

**Comment by energy718** [comment]
> 你好，按道理来说，你在 iframe 里载入远程模块，样式应该是挂到 iframe里的，你需要在外部使用的话，再次载入重新载入远程模块就可以了（因为 iframe 和 外面是两个独立的js运行时，需要各自独立引入）
> 
> 看了你的描述，感觉是bug？： 在 iframe 里引入的远程模块，样式挂到了外部 window 上？不会吧......

感谢您的回复 我按照您的方法试试看

**Comment by energy718** [comment]
> 如果你有此类特殊需求，你可以在远程组件载入成功后，调用
> 
> ```
> import { appStyleSrv } from 'hel-micro';
> 
> appStyleSrv.getStyleUrlList(); // 获得样式列表做额外操作
> ```

您好 我看您内部添加了`resetGlobalThis`用于重置内部环境 我想请问一下我下边的使用方法是不是有问题，Promise一直没返回也没有报错。。。
<img width="690" alt="image" src="https://user-images.githubusercontent.com/45483349/223686536-5026e8bd-15cb-4aa1-8adf-119308db0be8.png">

**Comment by energy718** [comment]
> > 如果你有此类特殊需求，你可以在远程组件载入成功后，调用
> > ```
> > import { appStyleSrv } from 'hel-micro';
> > 
> > appStyleSrv.getStyleUrlList(); // 获得样式列表做额外操作
> > ```
> 
> @fantasticsoul 您好 我看您内部添加了`resetGlobalThis`用于重置内部环境 我想请问一下我下边的使用方法是不是有问题，Promise一直没返回也没有报错。。。 <img alt="image" width="643" src="https://user-images.githubusercontent.com/45483349/223689730-112a89a9-ec86-4c8e-a649-7df5565cfcdb.png">
> 
> 但css js我看dom已经添加成功了 <img alt="image" width="1186" src="https://user-images.githubusercontent.com/45483349/223687697-acd3c134-6cad-4a43-9e17-730ce9446b86.png">

#52

**Comment by fantasticsoul** [comment]
已合入代码并发布hel-micro `3.13.12`

**Comment by energy718** [comment]
> 已合入代码并发布hel-micro `3.13.12`

十分感谢~
