### ISSUE TITLE
执行resetGlobalThis重置环境后，静态导入模块无法获取hel_proxy代理模块

### ISSUE THREAD

**Issue by energy718** [tnfe/hel#54]
使用`resetGlobalThis`后无法获取静态导入的hel_proxy代理模块
<img width="517" alt="image" src="https://user-images.githubusercontent.com/45483349/225506420-a8bb94d7-4c04-4cfd-83af-22e4d4721773.png">

不使用`resetGlobalThis`后可以正常获取
<img width="745" alt="image" src="https://user-images.githubusercontent.com/45483349/225506659-2d577aa8-640f-4aa6-8706-288f4eb257d7.png">

**Comment by fantasticsoul** [comment]
试试`exposeLib `函数能拿到么

```ts
import { exposeLib } from 'hel-lib-proxy';
const mod = exposeLib('hel-tpl-remote-lib');
console.log(mod);
```

**Comment by fantasticsoul** [comment]
如果是采用`import lib from 'hel-tpl-remote-lib'` 方式，这个场景注意控制 resetGlobalThis 一定要在 preFetchLib 之前执行，才能保证静态导入的模块是想要的模块

**Comment by energy718** [comment]
> 试试`exposeLib `函数能拿到么
> 
> ```ts
> import { exposeLib } from 'hel-lib-proxy';
> const mod = exposeLib('hel-tpl-remote-lib');
> console.log(mod);
> ```

这个可以拿到 这是不是意味着在这种场景下我无法使用静态模块的导入方式了，只能手动导出了

**Comment by energy718** [comment]
> 如果是采用`import lib from 'hel-tpl-remote-lib'` 方式，这个场景注意控制 resetGlobalThis 一定要在 preFetchLib 之前执行，才能保证静态导入的模块是想要的模块

这块儿我是这样做的  保证 resetGlobalThis 在 preFetchLib 之前
<img width="593" alt="image" src="https://user-images.githubusercontent.com/45483349/225526940-01b5db78-8b87-4c43-92d2-9c84aaf9592e.png">

**Comment by fantasticsoul** [comment]
addtThird 的调用时机必须是在 `await import('./loadApp')` 之前

**Comment by energy718** [comment]
> addtThird 的调用时机必须是在 `await import('./loadApp')` 之前

嗯 这个也是保证了的

**Comment by fantasticsoul** [comment]
这感觉很奇怪，可以提供一个可最新复现的仓库看看么

**Comment by energy718** [comment]
> 这感觉很奇怪，可以提供一个可最新复现的仓库看看么

好的 我研究一个仓库看看

**Comment by energy718** [comment]
> 这感觉很奇怪，可以提供一个可最新复现的仓库看看么

仓库示例： 

https://codesandbox.io/p/github/energy718/test-hel-iframe-example/main?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253A%2522clfav5kq4000dg4jyal3b4cm9%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clfau8svx000x3b6invvcpgjc%2522%253A%257B%2522key%2522%253A%2522clfau8svx000x3b6invvcpgjc%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522serve%2522%252C%2522port%2522%253A8080%252C%2522key%2522%253A%2522clfav6fv200c73b6jxcol6bqh%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522serve%2522%252C%2522key%2522%253A%2522clfav6dun007v3b6jm3bb4hrx%2522%252C%2522isMinimized%2522%253Atrue%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clfau8svx000x3b6invvcpgjc%2522%252C%2522spacesOrder%2522%253A%255B%2522clfau8svx000x3b6invvcpgjc%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D

**Comment by fantasticsoul** [comment]
好的，周末看下

**Comment by fantasticsoul** [comment]
你的代码有问题

![image](https://user-images.githubusercontent.com/7334950/225869591-65beeb46-b771-4a95-bae5-9b53b41df12f.png)

这段代码放入口文件执行，原入口文件内容下沉到`loadApp`文件，可参考这个[文件](https://github.com/hel-eco/hel-tpl-remote-lib/blob/master/src/index.ts)
``` 
export async function addThirdPartyDependencies(Vue) {
	resetGlobalThis(this);
	bindVueRuntime({ Vue });

	await preFetchLib('hel-tpl-remote-lib', {
		versionId: '2.1.2',
	});
  console.log('lib', lib)
}
```

目前你的代码不是我所说的那样。
![image](https://user-images.githubusercontent.com/7334950/225869945-cb99b572-55cf-4f8f-8ca9-10a6c6dbb1f7.png)

**Comment by energy718** [comment]
> 升级 hel-lib-proxy 到 3.13.1，然后基于最新版 hel-lib-proxy 打包一个子模块试试。

大佬我的示例写的是有点问题 我又修改了下示例  [仓库](https://github.com/energy718/test-hel-iframe-example)
我按照最新的`hel-lib-proxy 3.13.2` 重新打包了一个`hel-tpl-remote-lib` 测试了静态引入发现可以拿到了
![image](https://user-images.githubusercontent.com/45483349/225917466-d53ef0f0-2e06-4ddd-963c-ea5d6c0f13c3.png)

但是好像代码提示么得了。。。
![image](https://user-images.githubusercontent.com/45483349/225917318-91e3e525-9f06-4ec5-9eac-ebaf93e6afed.png)

**Comment by energy718** [comment]
> 升级 hel-lib-proxy 到 3.13.1，然后基于最新版 hel-lib-proxy 打包一个子模块试试。

额 `hel-tpl-remote-lib`还有个小问题 我看`replace-absolute-path`这个包也是您写的，这个删除代码好像在windows环境下没成功
![image](https://user-images.githubusercontent.com/45483349/225923297-b8646984-0bf8-4237-9bff-84154d1a2710.png)

这个`shx`的包是不是忘了加了。。。
![image](https://user-images.githubusercontent.com/45483349/225925286-1e2322f9-1fcd-43c0-97df-45c555858e6c.png)

**Comment by fantasticsoul** [comment]
好的我补一下，暂时你的主项目可以主动安装一下shx试试

**Comment by fantasticsoul** [comment]
缺类型是没有lilib目录导致的，看起来还是那个`replace-absolute-path`未执行成功导致的，你本地主项目安装下 shx 试试重打包发布
<img width="912" alt="image" src="https://user-images.githubusercontent.com/7334950/226072884-6f5f7515-91a9-479a-a9c8-228d582a4345.png">

**Comment by fantasticsoul** [comment]
安装最新版本`replace-absolute-path`，已添加`shx`依赖声明

**Comment by energy718** [comment]
> 缺类型是没有lib目录导致的，看起来还是那个`replace-absolute-path`未执行成功导致的，你本地主项目安装下 shx 试试重打包发布 <img alt="image" width="912" src="https://user-images.githubusercontent.com/7334950/226072884-6f5f7515-91a9-479a-a9c8-228d582a4345.png">

我更新了`replace-absolute-path`版本到最新版 重新打包了
![image](https://user-images.githubusercontent.com/45483349/226155917-cb5b3bff-4372-4a56-9f83-aec500c57252.png)
但还是没有代码提示。。。是哪里还有问题嘛
![image](https://user-images.githubusercontent.com/45483349/226155993-6151902f-4f2b-4277-9ee5-1b319057da4b.png)

**Comment by fantasticsoul** [comment]
会不会是 vetur 报的这个错误影响的？
<img width="569" alt="image" src="https://user-images.githubusercontent.com/7334950/226223206-be18aae8-f9da-4fbe-8710-065e59494f00.png">

我安装你的最新包后需要重启vscdoe，才能有类型提示，或者重启ts服务
<img width="617" alt="image" src="https://user-images.githubusercontent.com/7334950/226223273-f9a89ac3-6259-434f-880c-fe248c35f476.png">

效果如下
<img width="587" alt="image" src="https://user-images.githubusercontent.com/7334950/226223321-ec244cc2-3538-4d01-a68c-0bc79a994b26.png">
