### ISSUE TITLE
js克隆远程模块库，build失败

### ISSUE THREAD

**Issue by llm9131142671** [tnfe/hel#55]
npx degit https://github.com/hel-eco/hel-tpl-remote-lib  demo
npm run build 报错，这个问题和node版本有关吗，为什么报错呢

具体报错信息
| all files import statements been transformed to relative path for lib ^_^!

src/entrance/libTypes.ts → hel_proxy/entry.js...
[!] (plugin typescript) TypeError: hostOrText.readFile is not a function
TypeError: hostOrText.readFile is not a function

**Comment by fantasticsoul** [comment]
将typescript版本降低到 `4.8`即可，`4.9`存在这个[问题](https://github.com/microsoft/TypeScript/issues/51644)
