### ISSUE TITLE
修改unpkg 默认的host

### ISSUE THREAD

**Issue by kanouken** [tnfe/hel#58]
const subApp = helDevUtils.createVue3SubApp(pkg, { npmCdnType: 'unpkg', homePage: 'http://192.168.90.62:8080' });

这句话似乎不起作用，
build 后 metadata.json 里面的内容不正确
"htmlIndexSrc": "http://192.168.90.62:8080/index.html",

**Comment by fantasticsoul** [comment]
可以截图发下你整个 hel-meta.json 的结构么

**Comment by kanouken** [comment]
![企业微信截图_16796338836817](https://user-images.githubusercontent.com/4925886/227428306-bff2d21a-9795-49ba-a0eb-f5b97a7777c2.png)

**Comment by kanouken** [comment]
> 可以截图发下你整个 hel-meta.json 的结构么，顺带提供下你的 `hel-dev-utils` 版本号

"version": "2.3.1",

**Comment by fantasticsoul** [comment]
安装 v3 版本，并参考这个[地址](https://github.com/hel-eco/hel-tpl-remote-lib/blob/master/scripts/meta.js)，修改下meta文件再试试呢，我这里是正常的

**Comment by kanouken** [comment]
可以了 ，谢谢
