### ISSUE TITLE
提供和wujie一起使用的案例

### ISSUE THREAD

**Issue by ljquan** [tnfe/hel#6]

**Comment by fantasticsoul** [comment]
收到，后续会放出

**Comment by fantasticsoul** [comment]
已经在做案例，发现了一些问题：https://github.com/Tencent/wujie/issues/226，正在联系作者解决

**Comment by fantasticsoul** [comment]
已提供wujie与hel混合使用的例子（主要新增了远程组件，远程方法的示例）：
https://github.com/fantasticsoul/wujie-and-hel

clone 下来 pnpm i  , pnpm run start，然后访问react16项目即可
![image](https://user-images.githubusercontent.com/7334950/196335644-5a3dc10d-435a-41fb-9776-55ef9db18357.png)
![image](https://user-images.githubusercontent.com/7334950/196335653-50533fbf-2d52-47c9-b521-0a1d296c4267.png)
