### ISSUE TITLE
文档问题

### ISSUE THREAD

**Issue by lzp0301** [tnfe/hel#61]
https://tnfe.github.io/hel/docs/tutorial/%E5%AE%9E%E6%88%98/hel-antd

在【收益】的最后一句：“所用使用方就可以运行最新版本的 antd 了”
这里的“所用”是指的“所有”吗？

**Comment by fantasticsoul** [comment]
是的感谢指正

**Comment by fantasticsoul** [comment]
欢迎fork并提MR修正此问题

**Comment by fantasticsoul** [comment]
已修正，见地址：https://tnfe.github.io/hel/docs/tutorial/practise/hel-antd

**Comment by lzp0301** [comment]
痛失提交MR成为contributors的机会
