### ISSUE TITLE
文档问题

### ISSUE THREAD

**Issue by godkun** [tnfe/hel#62]
![image](https://user-images.githubusercontent.com/26134303/231038098-78efda9f-6c72-49d9-822e-a09abd7af6d9.png)

点击箭头处的链接，页面打不开

**Comment by fantasticsoul** [comment]
是这个地址 https://github.com/hel-eco/hel-tpl-remote-lib，欢迎fork并提MR修展此问题

**Comment by godkun** [comment]
> 是这个地址 [https://github.com/hel-eco/hel-tpl-remote-lib，](https://github.com/hel-eco/hel-tpl-remote-lib%EF%BC%8C) 欢迎fork并提MR修正此问题

好滴，已 pr

**Comment by fantasticsoul** [comment]
已合并，稍后发布

**Comment by fantasticsoul** [comment]
已发布最新文档 https://tnfe.github.io/hel/docs/tutorial/intro/
