### ISSUE TITLE
请问下使用ts，报错怎么处理呢

### ISSUE THREAD

**Issue by haibins** [tnfe/hel#66]
types没有用.d.ts，导致skipLibCheck无法生效。不能忽略ts报错
<img width="521" alt="image" src="https://user-images.githubusercontent.com/29914762/234204196-c28e46fd-ff0c-4bfe-af7b-1f29343c4410.png">
下面是ts报错：
<img width="1564" alt="image" src="https://user-images.githubusercontent.com/29914762/234203897-4f0ce0c1-4995-497f-b6cd-13f38f2639a0.png">

**Comment by fantasticsoul** [comment]
更新 hel-micro 到 `4.6.2` 即可，如果还有别的错误可以全部截图哈，你图里只能看到4个错误

**Comment by haibins** [comment]
好嘞，感谢大佬。试了一下还有这三处 error
<img width="1582" alt="image" src="https://user-images.githubusercontent.com/29914762/234454924-6390e8db-f183-49ed-abd1-57e9dce91f5f.png">


> 更新 hel-micro 到 `4.6.2` 即可，如果还有别的错误可以全部截图哈，你图里只能看到4个错误，见[提交](https://github.com/tnfe/hel/commit/9d7691c46bdd8cd6c9dbad4cf3e867e367cc64ef)

**Comment by fantasticsoul** [comment]
更新到 `4.6.3` 即可

**Comment by haibins** [comment]
非常感谢~
