### ISSUE TITLE
组件同时preFetchLib，经常会失败，会是什么情况，请问下有没有遇到过或者可能什么原因

### ISSUE THREAD

**Issue by haibins** [tnfe/hel#68]
代码是这样
<img width="591" alt="image" src="https://user-images.githubusercontent.com/29914762/235083893-cce7dbcc-3e35-4efe-b618-1684b60b11ae.png">

这是一个加载不出来的情况，大部分情况是这样
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/29914762/235083467-362e3341-3e0d-4ec2-8e63-e8a8e34a4256.png">
<img width="541" alt="image" src="https://user-images.githubusercontent.com/29914762/235084019-60b62392-e0fe-4324-8eb2-72c94b3ab385.png">

这是正常加载出来的情况，小概率成功
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/29914762/235083639-45c8a8e0-4ee6-4b19-b1c5-c7513a30d01a.png">
<img width="530" alt="image" src="https://user-images.githubusercontent.com/29914762/235083987-61f19435-c6b2-402b-ab75-fc5b3a02f197.png">

这是什么原因呢？

**Comment by haibins** [comment]
有一个会一直处于pending状态

**Comment by fantasticsoul** [comment]
你是请求的unpkg的还是你本地的呢，如果是unpkg的可以贴一个最小可复现的例子吗，如果是本地的，你确保你两个子模块里src的[LIB_NAME](https://github.com/hel-eco/hel-tpl-remote-react-comp/blob/master/src/configs/subApp.js) 声明没有重复哈，这个很重要

**Comment by haibins** [comment]
> 你是请求的unpkg的还是你本地的呢，如果是unpkg的可以贴一个最小可复现的例子吗，如果是本地的，你确保你两个子模块里src的[LIB_NAME](https://github.com/hel-eco/hel-tpl-remote-react-comp/blob/master/src/configs/subApp.js) 声明没有重复哈，这个很重要
<img width="574" alt="image" src="https://user-images.githubusercontent.com/29914762/236096998-d940d436-2afc-40dc-b279-c0dd97267f67.png">


是这样的，我两个组件分别请求的的是一个本地的，一个unpkg的包，但是版本是不一样的。[LIB_NAME](https://github.com/hel-eco/hel-tpl-remote-react-comp/blob/master/src/configs/subApp.js)是一致的，就相当于请求同一个包的不同版本，这样会有问题吗

**Comment by haibins** [comment]
<img width="808" alt="image" src="https://user-images.githubusercontent.com/29914762/236101454-70f90d83-a674-4838-b201-5882415900f1.png">

<img width="414" alt="image" src="https://user-images.githubusercontent.com/29914762/236101580-f71e11ea-cc21-40a6-9169-69a44696a5da.png">

这是两个组件同时请求的unpkg的同一个包的不同版本，这样是可以的。但是有一个换成本地的就不行了，就像这样
<img width="428" alt="image" src="https://user-images.githubusercontent.com/29914762/236102790-943cd7fb-d83e-45b9-9e9b-5d07f62a5bd0.png">

**Comment by fantasticsoul** [comment]
升级到最新版本`hel-micro`，请求本地开发模块时配置下 custom.trust = true 看下能否解决

**Comment by fantasticsoul** [comment]
已提供的可复现问题示例：https://github.com/haibins/remote-demo-master

**Comment by fantasticsoul** [comment]
经讨论，降低webpack chunk 数量后此问题不再复现

**Comment by fantasticsoul** [comment]
close issue
