### ISSUE TITLE
消费方报错

### ISSUE THREAD

**Issue by yoyooyooo** [tnfe/hel#7]
<img width="649" alt="image" src="https://user-images.githubusercontent.com/18062745/188279398-464f7a53-0794-4837-a0cd-f50c94aa3c5b.png">

```tsx
export default function HomePage() {
  useEffect(() => {
    bindReactRuntime({ React, ReactDOM });
  }, []);

  return (
    <div>
      <button
        onClick={() => {
          preFetchLib("hel-tpl-remote-react-comps-ts", {
            custom: { host: "http://localhost:3103", enable: !!location.port }
          })
            .then((res) => {
              console.log("远程包", res);
            })
            .catch(console.log);
        }}
      >
        test
      </button>
    </div>
  );
}
```

`hel-tpl-remote-react-comps-ts` 就是仓库里的模板，没做过改动

**Comment by fantasticsoul** [comment]
`bindReactRuntime({ React, ReactDOM })` 需要第一时间调用，通常在入口文件第一行调用，见示例
https://codesandbox.io/s/demo-load-remote-react-comp-2bnpl0

<img width="814" alt="image" src="https://user-images.githubusercontent.com/7334950/188281865-7c4aeb0d-094e-4fd4-9a8c-106398572f81.png">

**Comment by fantasticsoul** [comment]
我参考你这个例子改了一个，你可以看这个例子
https://codesandbox.io/s/naughty-kapitsa-e9ylji?file=/src/App.js

<img width="534" alt="image" src="https://user-images.githubusercontent.com/7334950/188281981-71e032c7-6b4f-40c0-9e9d-08d8c92d728d.png">

**Comment by starsoul666** [comment]
> 我参考你这个例子改了一个，你可以看这个例子 https://codesandbox.io/s/naughty-kapitsa-e9ylji?file=/src/App.js
> 
> <img alt="image" width="534" src="https://user-images.githubusercontent.com/7334950/188281981-71e032c7-6b4f-40c0-9e9d-08d8c92d728d.png">

这种方式preFetchLib获取的组件怎么使用呀？
定义了一个state, 把res设置进去，使用的使用报错，不是一个组件
const [Component, setComponent] = useState();

setComponent(res)

<Component />
