### ISSUE TITLE
npmmirror 镜像站已内置支持类似 unpkg cdn 解析能力，参考下？

### ISSUE THREAD

**Issue by GreatAuk** [tnfe/hel#70]
[npmmirror 镜像站已内置支持类似 unpkg cdn 解析能力](https://zhuanlan.zhihu.com/p/633904268)

或许可以参考下，看下 hel 是否可以接入。如果可以的话， 感觉对 hel 的推广有帮助。

**Comment by fantasticsoul** [comment]
可以试试资源替换钩子函数哈
https://tnfe.github.io/hel/docs/api/hel-micro/prefetch-lib#%E8%B5%84%E6%BA%90%E8%B7%AF%E5%BE%84%E6%9B%BF%E6%8D%A2
