### ISSUE TITLE
如何理解【工具链强绑定】

### ISSUE THREAD

**Issue by 2015214130** [tnfe/hel#73]
如题，如何理解文章中提到的难题之一【工具链强绑定】。
感谢

**Comment by fantasticsoul** [comment]
主要体现如下：
1 基于 webpack 5 构建的模块无法提供给vite 项目或其他构建工具的项目使用
2 webpack 4 3 2 项目必须升级到webpack 5 才能使用模块联邦技术

**Comment by fantasticsoul** [comment]
欢迎入群了解，有更详细的ppt介绍
