### ISSUE TITLE
npm发布带组织的包名如@xxx/xxx，使用preFetchLib("@xxx/xxx")获取不到元数据

### ISSUE THREAD

**Issue by lantingBoy** [tnfe/hel#74]
![481689312395_ pic](https://github.com/tnfe/hel/assets/22017210/546e5c15-a876-446e-a7e4-1c1a61da7caf)

**Comment by fantasticsoul** [comment]
目前版本在包名带组织时，获取元数据接口会拼接错误，上述问题理正确的元数据路径应该是
https://unpkg.com/@hdzk-hel/pangu@1.0.0/hel_dist/hel-meta.json

可使用元数据重置功能先规避这个问题
https://tnfe.github.io/hel/docs/api/hel-micro/prefetch-lib#%E9%87%8D%E7%BD%AE%E5%85%83%E6%95%B0%E6%8D%AE%E6%8E%A5%E5%8F%A3
