### ISSUE TITLE
关于micro-app和hel融合后部分动态资源加载失败问题

### ISSUE THREAD

**Issue by zhangbinzhbb** [tnfe/hel#77]
仓库：https://github.com/zhangbinzhbb/vue-admin-template
分支：dev_micro_app_hel_test
问题：关于micro-app与hel融合后动态资源加载失败
访问地址：http://localhost:9528/#/microAppTest

参考：micro-ap在线demo: http://www.micro-zoe.com/main-vue2/app-vue2/page2

有import { preFetchLib } from 'hel-micro' 引入
切换后，有资源加载失败

将import { preFetchLib } from 'hel-micro' 屏蔽掉后，就可以正常访问

**Comment by fantasticsoul** [comment]
已修复，见[提交](https://github.com/tnfe/hel/commit/da802d0c2c4a33bcb75b21dc781ac8d940b3ae73)，安装hel-micro最新版本`4.8.8`即可

**Comment by Torn1996** [comment]
最新版本，在micro-app和hel融合后js动态资源加载仍然会失败 @fantasticsoul
