### ISSUE TITLE
本地调试是否支持热更新？

### ISSUE THREAD

**Issue by hangaoke1** [tnfe/hel#79]
比如我应用是部署在线上的，通过 url debug 参数判断是否加载本地模块，此时本地模块修改代码后，应用能否实现热更新远程模块？

**Comment by fantasticsoul** [comment]
感觉理论上可行，你试试看呢，欢迎入群一起讨论

**Comment by hangaoke1** [comment]
测试可行
主应用：开发环境
库应用：开发环境
由于存在多个 react-refresh 实例，所以需要处理一下 react-refresh-webpack-plugin配置

hel react 模版调整
```js
// hel-tpl-remote-react-comp-ts/config/webpack.config.js
 new ReactRefreshWebpackPlugin({
    overlay: false,
    forceEnable: true,
    library: 'remoteRefresh', // 支持多实例
  }),
```

主应用：线上环境
库应用：开发环境

保证主应用在调试时加载 react development 包即可，可以考虑抽离 React、ReactDOM
```js
  externals: {
    react: 'React',
    'react-dom': 'ReactDOM',
  },
```
线上打包的时候可以打两份 html
- 一份 debug.html，加载开发模式 React （专门用来开启 debug 模式）
- 一份 index.htm，加载生产模式 React 包

后续有时间在补个 Demo 吧，目前测试完全没问题，热更新都 ok 的
