### ISSUE TITLE
请教一下关于hel-micro-core中源码的一个小问题

### ISSUE THREAD

**Issue by lzs246** [tnfe/hel#9]
在执行preFetchLib中，会去请求lib对应的hel-json，然后拿到lib对应的资源地址，加载完lib对应的资源后，然后会从cache的appName2verEmitLib中取出。

代码：
<img width="985" alt="image" src="https://user-images.githubusercontent.com/62453543/188302160-a91add8e-80a1-44c9-ab16-3c0bb9467608.png">

## 然后我这边疑问的是
**before打印**
<img width="536" alt="image" src="https://user-images.githubusercontent.com/62453543/188302212-459927b5-7134-40c5-84a2-20ec63fd66b8.png">

**after打印**
<img width="896" alt="image" src="https://user-images.githubusercontent.com/62453543/188302247-34a8e0b4-30e3-4e08-8266-1ea68222d0f7.png">

loadAssetsStarter函数又只去加载了lib的js和css，我没有弄明白appName2verEmitLib是从哪赋的值，是在lib的产物js中吗？还是说在别的地方呢？

麻烦大佬赐教

**Comment by fantasticsoul** [comment]
见`hel-lib-proxy`的`libReady`方法
https://github.com/tnfe/hel/blob/main/packages/hel-lib-proxy/src/index.ts
